name: cicd

on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yaml
      - dockerfile
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Short SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rafahueb/flask-beta3:${{ env.SHORT_SHA }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Install Argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/latest/download-argocd-linux-amd64
          chmod +x argocd
          mv ./argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: |
          argocd login https://argocd-server.argocd --insecure --grpc-web \
          -u admin -p ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app